### ISSUE TITLE
Roadmap

### ISSUE THREAD

**Issue by voldikss** [voldikss/vim-searchme#1]
- [x] __For open browser command behavior more robustly__: 
```vim
" windows
if has('win32') || has('win64')
      let cmd = '!start rundll32 url.dll,FileProtocolHandler %URL%'
" mac
elseif has('mac') || has('macunix') || has('gui_macvim') || system('uname') =~? '^darwin'
      let cmd = 'open %URL%'
" linux
elseif executable('xdg-open')
      let cmd = 'xdg-open %URL%'
```
For `!start rundll32 url.dll,FileProtocolHandler %URL%`, use `exec`, for ` open %URL%` and `xdg-open %URL%`, run `call system(cmd)`

**Comment by clouduan** [comment]
:memo:  __Memo__

- [ ] update readme: add __requirement__(VIM-8.0+/Neovim); __issue report__

**Comment by voldikss** [comment]
![image](https://user-images.githubusercontent.com/20282795/100518567-4f189580-31cd-11eb-91f1-4d9e70f5aa0a.png)
